name: CI (Java Gradle)

on:
  push:
    branches: [ "main", "develop" ]
    paths-ignore:
      # 문서만 변경 시 스킵
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths-ignore:
      # 문서만 변경 시 스킵
      - '**.md'
      - 'docs/**'

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}  # 그룹 지정
  cancel-in-progress: true  # 새로운 실행이 들어오면, 같은 그룹에 이미 돌고 있던 실행은 취소

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 커버리지 / 버전 태그 필요 시 유용

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle (cache on)
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build & Test
        run: ./gradlew clean build --no-daemon --stacktrace

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports-${{ github.sha }}
          path: |
            **/build/test-results/test
            **/build/reports/tests/test
          retention-days: 14  # artifact 보관 기간 설정

      - name: Upload jars
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: "**/build/libs/*.jar"

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
